設定ファイルをYAMLに変更した
su-its/bou-responder pull request #6
Opened 2021-05-28 07:55 UTC by h-takeyeah

ams-backendの設定ファイルをYAMLに変更したのに合わせてbou-responderの方もYAMLにしてみました(3月末に作ってあったのですがすっかり忘れていました)

ここまでpushしてこなかったのには、YAMLにする理由がなかったからなのかもしれないですが、記憶があいまいなので何とも言えないのと、自分では特にYAMLへの変更をrejectする理由も思いつかなかったのでPR出します

@equal-l2 さんから特になければ普通に某室での運用版にも入れたいと思いますのでよろしくお願いします

2021-05-28 07:56 UTC, h-takeyeah commented
YAMLへの変更に加え、ams-backendの方で上がった記法に関する修正など細かいリファクタリングも含みます

2021-05-29 05:38 UTC, equal-l2 requested changes

2021-05-29 05:38 UTC, equal-l2 commented on index.ts
> +    console.error('Some error occured while reading config file')
```suggestion
    console.error('Error occurred while reading config file')
```

2021-05-29 05:38 UTC, equal-l2 commented on tsconfig.json
> +    "target": "ES2017",                                /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
変更の理由はありますか？
（ターゲットを新しくすること自体はなんの問題もないのですが、何か理由があるなら聞いておきたい）

2021-05-29 05:40 UTC, equal-l2 commented on tsconfig.json
> +    "target": "ES2017",                                /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
あー、ES5だと`function`が使えないんですね
失礼しました

2021-05-29 05:42 UTC, equal-l2 commented on index.ts
> +    console.error("[!] The token doesn't have positive length.")
(ありえないですが)lengthが負数のチェックをしていないので、単に「長さが0だよ」と言ったほうが良いと思います

```suggestion
    console.error("[!] The length of token is zero")
```

2021-05-29 21:46 UTC, h-takeyeah commented on tsconfig.json
> +    "target": "ES2017",                                /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
それです！(自分でもなぜ更新したのだったか忘れてました……)

2021-05-29 21:53 UTC, h-takeyeah commented
指摘を修正しました。コミットが2つに分かれてしまいましたが大目に見てください……

2021-05-30 02:49 UTC, equal-l2 approved these changes

2021-05-31 05:31 UTC, merged